import Head from 'next/head'
import Link from "next/link"
import styles from '../styles/index.module.scss'

import { client } from "../libs/client"

import Test from "../src/components/Test"

const Index = ({blog, news}) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>NextJS microCMS Site</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Philosopher" />
      </Head>

      <main className={styles.main}>

        <Test
          message="test component"
        />

        {blog.map((article) => (
          <h2 key={article.id}>
            {article.title}
          </h2> 
        ))}

        {news.map((news) => (
          <h2 key={news.id}>
            {news.title}
          </h2> 
        ))}
      </main>
    </div>
  )
}

export default Index

export const getStaticProps = async () => {
  const blogData = await client.get<ResponseType>({
    endpoint: "blog",
  })

  const newsData = await client.get<ResponseType>({
    endpoint: "news",
    queries: {
      filters: "flag[equals]true",
    }
  })

  return {
    props: {
      blog: blogData.contents,
      news: newsData.contents
    }
  }
}